### ISSUE TITLE
Value labels in Select Multi component disappear during filtering

### ISSUE THREAD

**Issue by kufelkamil** [looker-open-source/components#2734]
Currently `values` parameter of `SelectMulti` is used for both rendering selected options and dropdown list.  If filtering is active and currently selection option is filtered out then it starts being represented using `value` instead of `label`, which causes bad user experience. 

working example: https://codesandbox.io/s/selectmulti-labels-filtering-52bs6

@looker/components version = 2.1.0

<img width="399" alt="Selected options is represented using label" src="https://user-images.githubusercontent.com/9267248/129367271-529d3ae8-fb62-4daf-8b02-b84e878aef27.png">
<img width="417" alt="Selected options is represented using value" src="https://user-images.githubusercontent.com/9267248/129367267-7acceca4-fd0b-4087-a80d-07fa9b926739.png">

**Comment by mdodgelooker** [comment]
Hi @kufelkamil thank you for submitting this issue. We are looking into a possible solution where `values` would be an array of objects just like `options` (i.e. `{ value: 'GB', label: 'United Kingdom' }`) instead of strings.

In the meantime, here are a couple workarounds that may work for you, depending on your use case:
https://codesandbox.io/s/selectmulti-labels-filtering-forked-w558i

Workaround 1: Keep options corresponding to current values in the filtered list, even when they don't match the filter term.
Workaround 2: Support filtering on the country abbreviation (`'GB'`) but only send the value to `options` (`{ value: 'United Kingdom' }`).
